source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
pod 'LTMorphingLabel'
pod 'Alamofire', '~> 3.0'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'
pod 'SnapKit', '~> 0.19.1'
pod 'Kingfisher', '~> 2.0'
pod 'ReactiveCocoa', '~> 2.5'
pod 'SVProgressHUD', '~> 2.0-beta'
pod 'MagicalRecord', '~> 2.3.0'
pod 'MJRefresh', '~> 3.0.7'